apiVersion: batch/v1
kind: Job
metadata:
  name: o2-mp-30-322
  namespace: kabdelma
spec:
  backoffLimit: 0
  template:
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: NotIn
                values:
                - major-gator
      containers:
      - args:
        - mpirun -np 16 --map-by hwthread /opt/vasp.6.1.2_pgi_mkl_beef/bin/vasp_std
          > vasp.out
        command:
        - /bin/bash
        - -c
        image: ulissigroup/kubeflow_vasp:amptorch
        imagePullPolicy: Always
        name: o2-mp-30-322
        resources:
          limits:
            cpu: 16
            memory: 32Gi
            nvidia.com/gpu: '0'
          requests:
            cpu: 16
            memory: 32Gi
        volumeMounts:
        - mountPath: /home/jovyan/shared-datasets/
          name: shared-datasets
        - mountPath: /home/jovyan/shared-scratch/
          name: shared-scratch
        - mountPath: /dev/shm
          name: dshm
        - mountPath: /home/jovyan/
          name: workspace-cop-model
        workingDir: /home/jovyan/shared-scratch/kabdelma/high_miller_idx/vasp/slabs/mp_30_322
      priorityClassName: default-priority
      restartPolicy: Never
      volumes:
      - name: shared-datasets
        persistentVolumeClaim:
          claimName: shared-datasets
      - name: shared-scratch
        persistentVolumeClaim:
          claimName: shared-scratch
      - emptyDir:
          medium: Memory
        name: dshm
      - name: workspace-cop-model
        persistentVolumeClaim:
          claimName: workspace-cop-model
  ttlSecondsAfterFinished: 7200
